[build]
command = """
  # Create Typst packages directory structure
  mkdir -p ~/.local/share/typst/packages/local/lilka/0.0.0/

  # Clone your package repository
  git clone https://github.com/syrkis/lilka.git ~/.local/share/typst/packages/local/lilka/0.0.0/

  # Download s3 images (for typst as it does not support remote url)
  git clone https://github.com/syrkis/s3.git /opt/build/repo/posts/s3

  # Run your regular build command
  npm run build
"""
publish = "dist"

[[redirects]]
from = "https://www.virian.org/*"
to = "https://virian.com/:splat"
status = 301
force = true
