[[redirects]]
  from = "/"
  to = "/ai-services"
  status = 301
  force = true

[[redirects]]
  from = "/ai-services"
  to = "/ai-services"
  status = 200

[[redirects]]
  from = "/*"
  to = "https://virian.org/:splat"
  status = 301
  force = true
