[build]
command = """
  # Initialize and update submodules to latest versions
  git submodule init
  git submodule update --remote --recursive

  # Create Typst packages directory structure
  mkdir -p ~/.local/share/typst/packages/local/lilka/0.0.0/

  # Clone your package repository
  git clone https://github.com/syrkis/lilka.git ~/.local/share/typst/packages/local/lilka/0.0.0/

  # Run your regular build command
  npm run build
"""
publish = "dist"

[[redirects]]
from = "https://www.virian.org/*"
to = "https://virian.com/:splat"
status = 301
force = true
