backend:
  name: git-gateway
  branch: main
  repo: syrkis/virian.org
  site_domain: virian.org

media_folder: static/images
public_folder: /images

collections:

  - name: "text"  # collection for writing
    label: "Text"
    folder: "src/lib/text"
    create: true
    slug: "{{slug}}"
    fields:
      - { name: "slug", label: "Slug", widget: "string" }
      - { name: "title", label: "Title", widget: "string" }
      - { name: "subtitle", label: "Subtitle", widget: "string" }
      - { name: "description", label: "Description", widget: "string" }      
      - { name: "date", label: "Date", widget: "datetime" }
      - { name: "body", label: "Body", widget: "markdown" }
      - { name: "image", label: "Image", widget: "image" }

  - name: "code"  # collection for data science projects
    label: "Code"
    folder: "src/lib/code"
    create: true
    slug: "{{slug}}"
    fields:
      - { name: "slug", label: "Slug", widget: "string" }
      - { name: "title", label: "Title", widget: "string" }
      - { name: "subtitle", label: "Subtitle", widget: "string" }
      - { name: "description", label: "Description", widget: "string" }
      - { name: "date", label: "Date", widget: "datetime" }
      - { name: "body", label: "Body", widget: "markdown" }
      - { name: "image", label: "Image", widget: "image" }
      - { name: "github", label: "Github", widget: "string" }