backend:
  name: git-gateway
  branch: main
  repo: syrkis/virian.org
  site_domain: virian.org

media_folder: static/images
public_folder: /images

collections:

  - name: "text"  # collection for writing
    label: "Text"
    folder: "src/lib/posts/text"
    create: true
    slug: "{{slug}}"
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "author", label: "Author", widget: "string" }
      - { name: "author_link", label: "Author Link", widget: "string" }
      - { name: "description", label: "Description", widget: "string" }
      - { name: "date", label: "Date", widget: "datetime" }
      - { name: "body", label: "Body", widget: "markdown" }
      - { name: "illustration", label: "Illustration", widget: "image" }
      - { name: "link", label: "Link", widget: "string" }

  - name: "code"  # collection for data science projects
    label: "Code"
    folder: "src/lib/posts/code"
    create: true
    slug: "{{slug}}"
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "description", label: "Description", widget: "string" }
      - { name: "date", label: "Date", widget: "datetime" }
      - { name: "body", label: "Body", widget: "markdown" }
      - { name: "illustration", label: "Illustration", widget: "image" }
      - { name: "link", label: "Link", widget: "string" }