backend:
  name: git-gateway
  branch: main
  repo: syrkis/virian.org
  site_domain: virian.org

media_folder: static/images
public_folder: /images

collections:

  - name: "code"  # collection for data science projects
    label: "Code"
    folder: "src/lib/code"
    create: true
    slug: "{{slug}}"
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "author", label: "Author", widget: "string", required: false }
      - { name: "subtitle", label: "Subtitle", widget: "string" }
      - { name: "description", label: "Description", widget: "string" }
      - { name: "date", label: "Date", widget: "datetime" }
      - { name: "body", label: "Body", widget: "markdown" }
      - { name: "image", label: "Image", widget: "image", required: false}
      - { name: "icon", label: "Image", widget: "image" }
      - { name: "github", label: "Github", widget: "string", required: false }
      - { name: "link", label: "Link", widget: "string", required: false }

  - name: "text"  # collection for writing
    label: "Text"
    folder: "src/lib/text"
    create: true
    slug: "{{slug}}"
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "author", label: "Author", widget: "string", required: false }
      - { name: "subtitle", label: "Subtitle", widget: "string" }
      - { name: "description", label: "Description", widget: "string" }      
      - { name: "date", label: "Date", widget: "datetime" }
      - { name: "body", label: "Body", widget: "markdown" }
      - { name: "image", label: "Image", widget: "image", required: false}
      - { name: "icon", label: "Image", widget: "string" }
      - { name: "link", label: "Link", widget: "image", required: false }
