backend:
  name: git-gateway
  branch: main
  repo: syrkis/virian.org
  site_domain: virian.org

media_folder: static/images
public_folder: /images

collections:

  - name: "posts"  # collection for writing
    label: "Posts"
    folder: "src/lib/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "authors", label: "Authors", widget: "list", fields: 
        [
          { name: "name", label: "Name", widget: "string" },
          { name: "email", label: "Email", widget: "string" },
          { name: "institution", label: "Institution", widget: "string" }
        ]}
      - { name: "description", label: "Description", widget: "string" }
      - { name: "date", label: "Date", widget: "datetime" }
      - { name: "body", label: "Body", widget: "markdown" }
      - { name: "illustration", label: "Illustration", widget: "image" }
      - { name: "keywords", label: "Keywords", widget: "list" }
      - { name: "category", label: "Category", widget: "string" }