backend:
  name: git-gateway
  branch: main
  repo: syrkis/virian.org
  site_domain: virian.org

media_folder: static/images
public_folder: /images

collections:

  - name: "opus"  # collection for writing
    label: "Opus"
    folder: "src/lib/opus"
    create: true
    slug: "{{slug}}"
    fields:
      - { name: "slug", label: "Slug", widget: "string" }
      - { name: "title", label: "Title", widget: "string" }
      - { name: "author", label: "Author", widget: "string" }
      - { name: "description", label: "Description", widget: "string" }
      - { name: "date", label: "Date", widget: "datetime" }
      - { name: "body", label: "Body", widget: "markdown" }
      - { name: "image", label: "Image", widget: "image" }
      - { name: "keywords", label: "Keywords", widget: "list", default: [] }
      - { name: "pubished", label: "Published", widget: "boolean", default: false }
      - { name: "category", label: "Category", widget: "string" }

  - name: "libris"
    label: "Libris"
    folder: "src/lib/libris"
    create: true
    slug: "{{slug}}"
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "author", label: "Author", widget: "string" }
      - { name: "description", label: "Description", widget: "string" }
      - { name: "date", label: "Date", widget: "datetime" }
      - { name: "Image", label: "Image", widget: "image" }
      - { name: "link", label: "Link", widget: "string" }
      - { name: "keywords", label: "Keywords", widget: "list" }
      - { name: "category", label: "Category", widget: "string" }
